name: user_app
description: 'MultiVendor App With Node and mongo.'

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rename: ^2.1.1
  get: ^4.6.5
  google_fonts: ^4.0.4
  cached_network_image: ^3.1.0
  carousel_slider: ^4.2.1
  smooth_page_indicator:
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.3
  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^15.1.1
  geocoding: ^3.0.0
  geolocator:
  location: ^5.0.3
  lottie: ^3.0.0
  shimmer: ^3.0.0
  intl:
  flutter_rating_bar:
  flutter_vector_icons:
  flutter_screenutil:
  google_maps_flutter:
  flutter_google_places:
  http:
  url_launcher: ^6.2.6
  image_picker:
  flutter_ringtone_player:
  rxdart:
  vibration:
  logger:
  google_maps_place_picker_mb:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/anime/
    - assets/icons/
    - assets/icons/
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
